// <auto-generated />
using System;
using EBOS.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EBOS.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250714112202_SehirIlceEkle")]
    partial class SehirIlceEkle
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("EBOS.Entities.Bilet", b =>
                {
                    b.Property<int>("BiletID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("BiletID"));

                    b.Property<decimal>("Fiyat")
                        .HasColumnType("decimal(65,30)");

                    b.Property<bool>("KampanyaUygulandiMi")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("KoltukID")
                        .HasColumnType("int");

                    b.Property<int>("KullaniciID")
                        .HasColumnType("int");

                    b.Property<DateTime>("SatinAlmaTarihi")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("SeansID")
                        .HasColumnType("int");

                    b.HasKey("BiletID");

                    b.HasIndex("KoltukID");

                    b.HasIndex("KullaniciID");

                    b.HasIndex("SeansID");

                    b.ToTable("Biletler");
                });

            modelBuilder.Entity("EBOS.Entities.Degerlendirme", b =>
                {
                    b.Property<int>("YorumID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("YorumID"));

                    b.Property<int>("EtkinlikID")
                        .HasColumnType("int");

                    b.Property<int>("KullaniciID")
                        .HasColumnType("int");

                    b.Property<int>("Puan")
                        .HasColumnType("int");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Yorum")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("YorumID");

                    b.HasIndex("EtkinlikID");

                    b.HasIndex("KullaniciID");

                    b.ToTable("Degerlendirmeler");
                });

            modelBuilder.Entity("EBOS.Entities.Etkinlik", b =>
                {
                    b.Property<int>("EtkinlikID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("EtkinlikID"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("EtkinlikAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("GorselYolu")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("IlceID")
                        .HasColumnType("int");

                    b.Property<int>("SureDakika")
                        .HasColumnType("int");

                    b.Property<int>("TurID")
                        .HasColumnType("int");

                    b.HasKey("EtkinlikID");

                    b.HasIndex("IlceID");

                    b.HasIndex("TurID");

                    b.ToTable("Etkinlikler");
                });

            modelBuilder.Entity("EBOS.Entities.EtkinlikTuru", b =>
                {
                    b.Property<int>("TurID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TurID"));

                    b.Property<string>("TurAdi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("TurID");

                    b.ToTable("EtkinlikTurleri");
                });

            modelBuilder.Entity("EBOS.Entities.Ilce", b =>
                {
                    b.Property<int>("IlceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IlceID"));

                    b.Property<string>("IlceAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("SehirID")
                        .HasColumnType("int");

                    b.HasKey("IlceID");

                    b.HasIndex("SehirID");

                    b.ToTable("Ilceler");
                });

            modelBuilder.Entity("EBOS.Entities.Kampanya", b =>
                {
                    b.Property<int>("KampanyaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("KampanyaID"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("BaslangicTarihi")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("BitisTarihi")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IndirimYuzdesi")
                        .HasColumnType("int");

                    b.Property<string>("KampanyaAdi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("KampanyaID");

                    b.ToTable("Kampanyalar");
                });

            modelBuilder.Entity("EBOS.Entities.Koltuk", b =>
                {
                    b.Property<int>("KoltukID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("KoltukID"));

                    b.Property<string>("KoltukNo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("SalonID")
                        .HasColumnType("int");

                    b.Property<int>("Satir")
                        .HasColumnType("int");

                    b.Property<int>("Sutun")
                        .HasColumnType("int");

                    b.HasKey("KoltukID");

                    b.HasIndex("SalonID");

                    b.ToTable("Koltuklar");
                });

            modelBuilder.Entity("EBOS.Entities.Kullanici", b =>
                {
                    b.Property<int>("KullaniciID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("KullaniciID"));

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Eposta")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("KullaniciID");

                    b.HasIndex("Eposta")
                        .IsUnique();

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("EBOS.Entities.Rapor", b =>
                {
                    b.Property<int>("RaporID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RaporID"));

                    b.Property<string>("DosyaYolu")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RaporAdi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("RaporID");

                    b.ToTable("Raporlar");
                });

            modelBuilder.Entity("EBOS.Entities.Salon", b =>
                {
                    b.Property<int>("SalonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SalonID"));

                    b.Property<string>("SalonAdi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("SatirSayisi")
                        .HasColumnType("int");

                    b.Property<int>("SutunSayisi")
                        .HasColumnType("int");

                    b.HasKey("SalonID");

                    b.ToTable("Salonlar");
                });

            modelBuilder.Entity("EBOS.Entities.Seans", b =>
                {
                    b.Property<int>("SeansID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SeansID"));

                    b.Property<int>("EtkinlikID")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("Saat")
                        .HasColumnType("time(6)");

                    b.Property<int>("SalonID")
                        .HasColumnType("int");

                    b.Property<string>("SeansAdi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime(6)");

                    b.HasKey("SeansID");

                    b.HasIndex("EtkinlikID");

                    b.HasIndex("SalonID");

                    b.ToTable("Seanslar");
                });

            modelBuilder.Entity("EBOS.Entities.Sehir", b =>
                {
                    b.Property<int>("SehirID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SehirID"));

                    b.Property<string>("SehirAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("SehirID");

                    b.ToTable("Sehirler");
                });

            modelBuilder.Entity("EBOS.Entities.Bilet", b =>
                {
                    b.HasOne("EBOS.Entities.Koltuk", "Koltuk")
                        .WithMany("Biletler")
                        .HasForeignKey("KoltukID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EBOS.Entities.Kullanici", "Kullanici")
                        .WithMany("Biletler")
                        .HasForeignKey("KullaniciID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EBOS.Entities.Seans", "Seans")
                        .WithMany("Biletler")
                        .HasForeignKey("SeansID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Koltuk");

                    b.Navigation("Kullanici");

                    b.Navigation("Seans");
                });

            modelBuilder.Entity("EBOS.Entities.Degerlendirme", b =>
                {
                    b.HasOne("EBOS.Entities.Etkinlik", "Etkinlik")
                        .WithMany("Degerlendirmeler")
                        .HasForeignKey("EtkinlikID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EBOS.Entities.Kullanici", "Kullanici")
                        .WithMany("Degerlendirmeler")
                        .HasForeignKey("KullaniciID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Etkinlik");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("EBOS.Entities.Etkinlik", b =>
                {
                    b.HasOne("EBOS.Entities.Ilce", "Ilce")
                        .WithMany("Etkinlikler")
                        .HasForeignKey("IlceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EBOS.Entities.EtkinlikTuru", "EtkinlikTuru")
                        .WithMany("Etkinlikler")
                        .HasForeignKey("TurID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EtkinlikTuru");

                    b.Navigation("Ilce");
                });

            modelBuilder.Entity("EBOS.Entities.Ilce", b =>
                {
                    b.HasOne("EBOS.Entities.Sehir", "Sehir")
                        .WithMany("Ilceler")
                        .HasForeignKey("SehirID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sehir");
                });

            modelBuilder.Entity("EBOS.Entities.Koltuk", b =>
                {
                    b.HasOne("EBOS.Entities.Salon", "Salon")
                        .WithMany("Koltuklar")
                        .HasForeignKey("SalonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Salon");
                });

            modelBuilder.Entity("EBOS.Entities.Seans", b =>
                {
                    b.HasOne("EBOS.Entities.Etkinlik", "Etkinlik")
                        .WithMany("Seanslar")
                        .HasForeignKey("EtkinlikID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EBOS.Entities.Salon", "Salon")
                        .WithMany("Seanslar")
                        .HasForeignKey("SalonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Etkinlik");

                    b.Navigation("Salon");
                });

            modelBuilder.Entity("EBOS.Entities.Etkinlik", b =>
                {
                    b.Navigation("Degerlendirmeler");

                    b.Navigation("Seanslar");
                });

            modelBuilder.Entity("EBOS.Entities.EtkinlikTuru", b =>
                {
                    b.Navigation("Etkinlikler");
                });

            modelBuilder.Entity("EBOS.Entities.Ilce", b =>
                {
                    b.Navigation("Etkinlikler");
                });

            modelBuilder.Entity("EBOS.Entities.Koltuk", b =>
                {
                    b.Navigation("Biletler");
                });

            modelBuilder.Entity("EBOS.Entities.Kullanici", b =>
                {
                    b.Navigation("Biletler");

                    b.Navigation("Degerlendirmeler");
                });

            modelBuilder.Entity("EBOS.Entities.Salon", b =>
                {
                    b.Navigation("Koltuklar");

                    b.Navigation("Seanslar");
                });

            modelBuilder.Entity("EBOS.Entities.Seans", b =>
                {
                    b.Navigation("Biletler");
                });

            modelBuilder.Entity("EBOS.Entities.Sehir", b =>
                {
                    b.Navigation("Ilceler");
                });
#pragma warning restore 612, 618
        }
    }
}
